src/components/AppLogo.vue
src/components/LayoutNavbar.vue
src/components/NavbarItem.vue
src/components/NavbarTogo.vue

Extract components from the LayoutNavbar - was a good exercise in Vue component structure & usage.

Patch | Layout Components

---

.vscode/extensions.json
package-lock.json
src/components/AboutSection.vue
src/components/CheckedList/CheckedList.vue
src/components/CheckedList/ListItem.vue
src/components/SectionSeparator.vue
src/components/StyledLink.vue
src/pages/AboutPage.vue

Just the about page - starting with the easy ones.
API calls are blocked on dev - could you add a CORS exception for it on the service @nosvalds - not confident how to do it for this - for the local dev, I had to set the port to 4200 for this instance as well.

Page | About

---

src/utils/document.js

[Trello Ticket](https://trello.com/c/BqecAw5Y/270-long-filename-handling-on-organisation-page)

Decode document URL before extracting fileName

---

src/utils/document.js

This is in response to added feedback on the datastore availability ticket

Fix | Missed Edge Case Datastore Availability

---

src/pages/OrganisationPage.vue
src/pages/ReportPage.vue
src/utils/api/documents.js
src/utils/api/organisations.js
src/utils/document.js

Ticket [https://trello.com/c/O4RGwcIz/275-front-end-displays-a-valid-validation-report-for-file-without-a-validation-report](https://trello.com/c/O4RGwcIz/275-front-end-displays-a-valid-validation-report-for-file-without-a-validation-report) and [https://trello.com/c/2y3RAL5a/320-add-proper-404-error-handling-as-well-as-handling-for-incorrect-organisations-and-reports](https://trello.com/c/2y3RAL5a/320-add-proper-404-error-handling-as-well-as-handling-for-incorrect-organisations-and-reports)

Feature | 404 Error Handling

---

.github/workflows/main_CD.yml
.github/workflows/main_CI.yml
envs/.env.production

Adds CI / CD to the prod environment

Add CI and CD for production

---

.github/workflows/main_CD.yml
cypress.config.prod.js

Fixes to production deployment that need to be merged back into develop

Production deployment

---

src/components/RemoteFIlesValidator.vue

[Trello](https://trello.com/c/kvAjOprK)

label url input for accessibility

---

src/components/organisation/DocumentList.vue
src/components/organisation/DocumentListItem.vue

[Trello](https://trello.com/c/7fHntCUa)

Fix org page link for files that fail download

---

.github/workflows/develop_CD.yml
.github/workflows/main_CD.yml
cypress.config.dev.js
cypress.config.prod.js
envs/.env.development
envs/.env.production

[Trello](https://trello.com/c/NviNp8p4)

update to domains for v2.5.0 go-live

---

src/pages/AboutPage.vue
src/pages/HomePage.vue

[Trello](https://trello.com/c/XDNfcF6q)

update to new QA for ALV II launch

---

src/components/layout/LayoutFooter.vue

[Trello](https://trello.com/c/MfnA0DeN)

fix link to github release

---

src/components/NotificationBanner.vue

[Trello](https://trello.com/c/nwkrMAbx)

update banner now that all reports are transitioned

---

src/components/organisation/OrganisationsList.vue

[Trello](https://trello.com/c/m0gJeKYk)

add padding to organisation link list for google search console error

---

.github/workflows/main_CD.yml
.github/workflows/main_CI.yml

[Trello](https://trello.com/c/zzhYaIFf)

fix prod ci cd for cypress tests

---

cypress/integration/publicData.spec.js
src/components/organisation/DocumentListItem.vue
src/components/report/DocumentInfo.vue
src/components/report/ReportDocumentStatus.vue
src/pages/ReportPage.vue

Ticket https://trello.com/c/bFc91Tzs/250-make-report-page-display-status-table-row-from-organisation-page

Feature | Report Status Row

---

cypress/fixtures/validationReport.json
cypress/integration/validationReport.spec.js
src/components/report/FeedbackItem.vue
src/utils/document.js

Ticket https://trello.com/c/sXS8wOQ9/241-highlight-blank-space-in-attribute-codes
My solution here was pretty much displaying a further error message to highlight the space, as was the most feasible

Feature | Error space highlight

---

src/utils/document.js

https://github.com/IATI/refresher/pull/278
https://iaticonnect.org/group/9/topic/proposed-update-iati-datastore

Organisation page - look at new last_solrize_end field and show "Old version"

---

cypress/fixtures/incorrect-extension.txt
cypress/integration/checkData.spec.js
src/components/LocalFilesValidator.vue
src/utils/api/validate.js

See https://github.com/IATI/validator-web/issues/558

Show error when file upload fails

---

src/components/RemoteFIlesValidator.vue
src/pages/ReportPage.vue

Spelling error

---

src/components/report/FeedbackItem.vue

- Style rule ids as bold
- Style feedback message as code

Add styles to Report page feedback items

---

src/components/FileStatusInfo.vue
src/components/organisation/DocumentList.vue
src/components/organisation/OrganisationAlphabetNavigator.vue
src/components/organisation/OrganisationsList.vue
src/pages/HomePage.vue
src/pages/OrganisationsPage.vue
src/pages/ReportPage.vue

A few visual changes and some text wording, typo fixes etc.

Fixing various snags

---

src/components/organisation/DocumentListItem.vue
src/components/report/FeedbackItem.vue
src/components/report/ReportDocumentStatus.vue

Two small visual snags:
- Removing a bullet point
- Fixing some vertical alignment of cells in a table

Visual snags
